select * from customer limit 20

--Q1) What is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as revenue
from customer
group by gender

--Q2) Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount 
from customer
where discount_applied = 'Yes' and purchase_amount >=(select avg(purchase_amount) from customer)

--Q3) Which are the top 5 products with highest average review rating?

select item_purchased,round(avg(review_rating::numeric),2) as highest_rating_avg
from customer
group by item_purchased
order by highest_rating_avg desc
limit 5;

--Q4) Compare the average purchase amounts between standard and express shipping. 
select shipping_type,round(avg(purchase_amount),2) 
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5) Do subscribed customers spend more? compare average spend and total revenue
-- between subcribed and non-subscribers.
select subscription_status
,count(customer_id) as total_customer
,round(avg(purchase_amount::numeric),2) as avg_spend
,round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6) Which 5 products have the highest precentage of purchases with discounts applied?
select item_purchased,
round(100*sum(case when discount_applied ='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7)******** Segment customers into New,Returning and loyal based on their total
--number of previous purchases, and show the count of each segment.******
with customer_type as(
select customer_id,previous_purchases,
case 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment,count(*)as Number_of_Customers
from customer_type
group by customer_segment

--Q8) What are the top 3 most purchased products within each category?
with item_counts as
(select category
,item_purchased
,count(customer_id) as total_orders
,row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer 
group by category, item_purchased
)

select item_rank , category , item_purchased, total_orders
from item_counts
where item_rank <= 3;
-- WE DID NOT USED RANK HERE BECAUSE IT CONTAINS DUPLICATES 
-- RECORD AND RANKS WOULD ASSIGN SAME NO. TOT THESE RECORDS
-- BUT SINCE WE WANT 3 DIFFERENT RANK ROW_NUMBER IS SUITABLE HERE.

--Q9) Are customers who are repeat buyers (more than 5 previous purchases) 
--also likely to subscribe ************************************
--imp because if repeat buyers are also ssubscribers that great for the bussiness


select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >= 5 
group by subscription_status

--Q10 What is the revenue contribution of each age group?
select age_group , sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc